

module.exports = {
    BASE_URL: "https://batutto.com",
    LOAD_RESTAURANTS: "LOAD_RESTAURANTS",
    CHANGE_USERNAME: "CHANGE_USERNAME", 
    LOAD_FILTERS: "LOAD_FILTERS",
    SET_FILTER: "SET_FILTER",

    SUCCESS: "_SUCCESS",
    FAIL: "_FAIL",
    START: "_START"
}